# RISC-V 64-bit 工具链配置文件
# 使用方法: cmake -B build -DCMAKE_TOOLCHAIN_FILE=riscv64-toolchain.cmake

SET (CMAKE_SYSTEM_NAME Generic)
SET (CMAKE_SYSTEM_PROCESSOR riscv64)

# 工具链前缀
SET (TOOLCHAIN_PREFIX riscv64-linux-gnu)

# 编译器设置
SET (CMAKE_C_COMPILER ${TOOLCHAIN_PREFIX}-gcc)
SET (CMAKE_CXX_COMPILER ${TOOLCHAIN_PREFIX}-g++)
SET (CMAKE_ASM_COMPILER ${TOOLCHAIN_PREFIX}-gcc)

# 工具设置
SET (CMAKE_OBJCOPY ${TOOLCHAIN_PREFIX}-objcopy)
SET (CMAKE_OBJDUMP ${TOOLCHAIN_PREFIX}-objdump)
SET (CMAKE_SIZE ${TOOLCHAIN_PREFIX}-size)
SET (CMAKE_NM ${TOOLCHAIN_PREFIX}-nm)
SET (CMAKE_STRIP ${TOOLCHAIN_PREFIX}-strip)

# 搜索路径配置
SET (CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET (CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET (CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
SET (CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

# 跳过编译器测试（裸机环境）
SET (CMAKE_C_COMPILER_WORKS 1)
SET (CMAKE_CXX_COMPILER_WORKS 1)
